<?php

/**
 * Adds plugin styles to pages.
 * Implements hook_preprocess_HOOK().
 */
function ucb_ckeditor_plugins_preprocess_field(array &$variables) {
	$fieldType = $variables['field_type'];
	if($fieldType == 'text_long' || $fieldType == 'text_with_summary') // Indicates a rich text field
		$variables['#attached']['library'][] = 'ucb_ckeditor_plugins/ckeditor-plugin-styles';
}

/**
 * Implements hook_theme().
 */
function ucb_ckeditor_plugins_theme() {
	return [
		'ucb_campus_map_embed' => [
			'variables' => [
				'attributes' => [],
				'mapLocation' => ''
			]
		]
	];
}
